### ISSUE TITLE
cliTable2Json is not a function

### ISSUE THREAD

**Issue by aileo** [Quobject/cli-table-2-json#1]
Hello,

I am using your [docker-cli-js](https://github.com/Quobject/docker-cli-js) and since today I can't anymore as it throws me an error. I investigate a bit and it seems to be a problem from this project.

1.0.8:
```js
var cliTable2Json = require('cli-table-2-json');
console.log(cliTable2Json);
// { cliTable2Json: [Function: cliTable2Json] }
```
1.0.1:
```js
var cliTable2Json = require('cli-table-2-json');
console.log(cliTable2Json);
// { cliTable2Json: [Function: cliTable2Json] }
```

1.0.0:
```js
var cliTable2Json = require('cli-table-2-json');
console.log(cliTable2Json);
// [Function]
```

I think it is related to the build process but i don't understand typescript enough to tell you what.
Would you accept a PR for this issue ?

**Comment by mattqs** [comment]
Sorry, I did some breaking changes in `cli-table-2-json` by moving to typescript. There will be an updated version of docker-cli-js that will working with the typescript version.

**Comment by mattqs** [comment]
Please use new `docker-cli-js` version:
https://github.com/Quobject/docker-cli-js/releases/tag/2.0.1

**Comment by aileo** [comment]
Great, thank you for your quick response and action !
