### ISSUE TITLE
cliTable2Json is not a function

### ISSUE THREAD

**Issue by Kryptonous** [Quobject/cli-table-2-json#2]
Hi, 

Whenever I try running the script, it gives me the following error: `cliTable2Json is not a function.`
Same error when using the given example.

I read that you had the same issue with the docker-version, maybe the same solution can be applied?

**Comment by mattqs** [comment]
Use the latest version 1.0.8 of cli-table-2-json: 
 `"cli-table-2-json": "^1.0.8",`

**Comment by mattqs** [comment]
I've updated readme to correct example error:
```
var cliTable2Json = require('cli-table-2-json');

var lines = ['NAME      ACTIVE   DRIVER      STATE     URL                         SWARM',
              'consul1   -        amazonec2   Running   tcp://54.175.200.212:2376   ',
              'consul2   -        amazonec2   Running   tcp://52.23.236.38:2376     ',
              'consul3   -        amazonec2   Running   tcp://54.85.111.241:2376    ',
              ''];

var result = cliTable2Json.cliTable2Json(lines);
```

**Comment by Kryptonous** [comment]
Thanks a lot for the quick reply!
